default_language: "en_US"

features:
  global_list:
    enabled: true
    command: glist
    aliases:
      - globallist
      - list
      - players
    max-servers: 9
    progress:
      count: 45
      complete: "|"
      not_complete: "<gray>|"
    server:
      BedWarsMain:
        sum:
          - "bw-server-1"
          - "bw-server-2"
          - "bw-server-3"
      bw-server-1:
        hidden: true
      bw-server-2:
        hidden: true
      bw-server-3:
        hidden: true
    vanish:
      decoration:
        server: "<yellow>$server</yellow>"
        player: "<red>$player</red>"

  find:
    enabled: true
    command: find
    aliases: []

  send:
    enabled: true
    command: send
    aliases: []

  alert:
    enabled: true
    command: alert
    aliases: []

  broadcast:
    enabled: true
    command: broadcast
    aliases:
      - bc

  ping:
    enabled: true
    command: ping
    aliases: []

  kickall:
    enabled: true
    command: kickall
    aliases: []

  move:
    enabled: true
    command: move
    aliases: []

startup_commands: []
